swagger:
  info:
    build:
      version: @project.version@
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subbaraju_distribution?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

