swagger:
  info:
    build:
      version: @project.version@
spring:
  datasource:
    name: testdb
    driver-class-name: org.h2.Driver
    initialize: false
    url: jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;ALIAS_COLUMN_NAME=TRUE;
  h2:
    console:
      enabled: true

